// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// run_mcmc
Rcpp::List run_mcmc(arma::mat response, arma::mat design, arma::mat basis, arma::vec time, arma::mat penalty, arma::uword ldim, arma::uword iter, arma::uword burnin, arma::uword thin, Rcpp::Nullable<Rcpp::List> init_, std::string covstruct);
RcppExport SEXP _rrbfda_run_mcmc(SEXP responseSEXP, SEXP designSEXP, SEXP basisSEXP, SEXP timeSEXP, SEXP penaltySEXP, SEXP ldimSEXP, SEXP iterSEXP, SEXP burninSEXP, SEXP thinSEXP, SEXP init_SEXP, SEXP covstructSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type response(responseSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type design(designSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type basis(basisSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time(timeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< arma::uword >::type ldim(ldimSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type init_(init_SEXP);
    Rcpp::traits::input_parameter< std::string >::type covstruct(covstructSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mcmc(response, design, basis, time, penalty, ldim, iter, burnin, thin, init_, covstruct));
    return rcpp_result_gen;
END_RCPP
}
// get_delta_eta_density
double get_delta_eta_density(arma::mat& delta_eta1, arma::mat& delta_eta2, arma::mat& eta, arma::mat& beta, arma::mat& xi_eta, arma::mat& design);
RcppExport SEXP _rrbfda_get_delta_eta_density(SEXP delta_eta1SEXP, SEXP delta_eta2SEXP, SEXP etaSEXP, SEXP betaSEXP, SEXP xi_etaSEXP, SEXP designSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta1(delta_eta1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta2(delta_eta2SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xi_eta(xi_etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type design(designSEXP);
    rcpp_result_gen = Rcpp::wrap(get_delta_eta_density(delta_eta1, delta_eta2, eta, beta, xi_eta, design));
    return rcpp_result_gen;
END_RCPP
}
// get_delta_eta_proposal
Rcpp::List get_delta_eta_proposal(arma::mat& delta_eta1, arma::mat& delta_eta2);
RcppExport SEXP _rrbfda_get_delta_eta_proposal(SEXP delta_eta1SEXP, SEXP delta_eta2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta1(delta_eta1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta2(delta_eta2SEXP);
    rcpp_result_gen = Rcpp::wrap(get_delta_eta_proposal(delta_eta1, delta_eta2));
    return rcpp_result_gen;
END_RCPP
}
// get_delta_eta1_grad
double get_delta_eta1_grad(arma::mat& delta_eta1, arma::mat& delta_eta2, arma::mat& eta, arma::mat& beta, arma::mat& xi_eta, arma::mat& design, arma::uword r, arma::uword c);
RcppExport SEXP _rrbfda_get_delta_eta1_grad(SEXP delta_eta1SEXP, SEXP delta_eta2SEXP, SEXP etaSEXP, SEXP betaSEXP, SEXP xi_etaSEXP, SEXP designSEXP, SEXP rSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta1(delta_eta1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta2(delta_eta2SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xi_eta(xi_etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(get_delta_eta1_grad(delta_eta1, delta_eta2, eta, beta, xi_eta, design, r, c));
    return rcpp_result_gen;
END_RCPP
}
// get_delta_eta2_grad
double get_delta_eta2_grad(arma::mat& delta_eta1, arma::mat& delta_eta2, arma::mat& eta, arma::mat& beta, arma::mat& xi_eta, arma::mat& design, arma::uword c, arma::uword l);
RcppExport SEXP _rrbfda_get_delta_eta2_grad(SEXP delta_eta1SEXP, SEXP delta_eta2SEXP, SEXP etaSEXP, SEXP betaSEXP, SEXP xi_etaSEXP, SEXP designSEXP, SEXP cSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta1(delta_eta1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta2(delta_eta2SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xi_eta(xi_etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type c(cSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(get_delta_eta2_grad(delta_eta1, delta_eta2, eta, beta, xi_eta, design, c, l));
    return rcpp_result_gen;
END_RCPP
}
// compute_delta_eta_density_c
double compute_delta_eta_density_c(arma::mat& delta_eta1, arma::mat& delta_eta2, arma::mat& eta, arma::mat& beta, arma::mat& xi_eta, arma::mat& design, arma::uword c, double a1, double a2, double a3, double a4);
RcppExport SEXP _rrbfda_compute_delta_eta_density_c(SEXP delta_eta1SEXP, SEXP delta_eta2SEXP, SEXP etaSEXP, SEXP betaSEXP, SEXP xi_etaSEXP, SEXP designSEXP, SEXP cSEXP, SEXP a1SEXP, SEXP a2SEXP, SEXP a3SEXP, SEXP a4SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta1(delta_eta1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta2(delta_eta2SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xi_eta(xi_etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< double >::type a2(a2SEXP);
    Rcpp::traits::input_parameter< double >::type a3(a3SEXP);
    Rcpp::traits::input_parameter< double >::type a4(a4SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_delta_eta_density_c(delta_eta1, delta_eta2, eta, beta, xi_eta, design, c, a1, a2, a3, a4));
    return rcpp_result_gen;
END_RCPP
}
// compute_delta_eta_density_c2
double compute_delta_eta_density_c2(arma::mat& delta_eta1, arma::mat& delta_eta2, arma::vec& delta_eta3, arma::mat& eta, arma::mat& beta, arma::mat& xi_eta, arma::mat& design, arma::uword c);
RcppExport SEXP _rrbfda_compute_delta_eta_density_c2(SEXP delta_eta1SEXP, SEXP delta_eta2SEXP, SEXP delta_eta3SEXP, SEXP etaSEXP, SEXP betaSEXP, SEXP xi_etaSEXP, SEXP designSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta1(delta_eta1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type delta_eta2(delta_eta2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type delta_eta3(delta_eta3SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xi_eta(xi_etaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type design(designSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_delta_eta_density_c2(delta_eta1, delta_eta2, delta_eta3, eta, beta, xi_eta, design, c));
    return rcpp_result_gen;
END_RCPP
}
// identify_delta1
arma::vec identify_delta1(arma::vec& input);
RcppExport SEXP _rrbfda_identify_delta1(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(identify_delta1(input));
    return rcpp_result_gen;
END_RCPP
}
// identify_delta2
arma::rowvec identify_delta2(arma::rowvec& input);
RcppExport SEXP _rrbfda_identify_delta2(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec& >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(identify_delta2(input));
    return rcpp_result_gen;
END_RCPP
}
// gam_trunc_left
double gam_trunc_left(double a, double b, double cut);
RcppExport SEXP _rrbfda_gam_trunc_left(SEXP aSEXP, SEXP bSEXP, SEXP cutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type cut(cutSEXP);
    rcpp_result_gen = Rcpp::wrap(gam_trunc_left(a, b, cut));
    return rcpp_result_gen;
END_RCPP
}
// gam_trunc_right
double gam_trunc_right(double a, double b, double cut);
RcppExport SEXP _rrbfda_gam_trunc_right(SEXP aSEXP, SEXP bSEXP, SEXP cutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type cut(cutSEXP);
    rcpp_result_gen = Rcpp::wrap(gam_trunc_right(a, b, cut));
    return rcpp_result_gen;
END_RCPP
}
// normal_trunc_left
double normal_trunc_left(double a, double b, double cut);
RcppExport SEXP _rrbfda_normal_trunc_left(SEXP aSEXP, SEXP bSEXP, SEXP cutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type cut(cutSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_trunc_left(a, b, cut));
    return rcpp_result_gen;
END_RCPP
}
// reshape_nreg
arma::mat reshape_nreg(arma::mat eta, arma::uword nsub, arma::uword nreg);
RcppExport SEXP _rrbfda_reshape_nreg(SEXP etaSEXP, SEXP nsubSEXP, SEXP nregSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nsub(nsubSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type nreg(nregSEXP);
    rcpp_result_gen = Rcpp::wrap(reshape_nreg(eta, nsub, nreg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rrbfda_run_mcmc", (DL_FUNC) &_rrbfda_run_mcmc, 11},
    {"_rrbfda_get_delta_eta_density", (DL_FUNC) &_rrbfda_get_delta_eta_density, 6},
    {"_rrbfda_get_delta_eta_proposal", (DL_FUNC) &_rrbfda_get_delta_eta_proposal, 2},
    {"_rrbfda_get_delta_eta1_grad", (DL_FUNC) &_rrbfda_get_delta_eta1_grad, 8},
    {"_rrbfda_get_delta_eta2_grad", (DL_FUNC) &_rrbfda_get_delta_eta2_grad, 8},
    {"_rrbfda_compute_delta_eta_density_c", (DL_FUNC) &_rrbfda_compute_delta_eta_density_c, 11},
    {"_rrbfda_compute_delta_eta_density_c2", (DL_FUNC) &_rrbfda_compute_delta_eta_density_c2, 8},
    {"_rrbfda_identify_delta1", (DL_FUNC) &_rrbfda_identify_delta1, 1},
    {"_rrbfda_identify_delta2", (DL_FUNC) &_rrbfda_identify_delta2, 1},
    {"_rrbfda_gam_trunc_left", (DL_FUNC) &_rrbfda_gam_trunc_left, 3},
    {"_rrbfda_gam_trunc_right", (DL_FUNC) &_rrbfda_gam_trunc_right, 3},
    {"_rrbfda_normal_trunc_left", (DL_FUNC) &_rrbfda_normal_trunc_left, 3},
    {"_rrbfda_reshape_nreg", (DL_FUNC) &_rrbfda_reshape_nreg, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rrbfda(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
