# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run Markov-Chain Monte-Carlo
#'
#' Generate samples from the posterior distribution using Gibbs sampling and 
#' Metropolis-Hastings steps
#' @param response N x T response matrix, where N is number of subjects and T is number
#' of time points. Values can be NA if there's missing data
#' @param design N x d_{1} design matrix for mean structure
#' @param basis T x p basis matrix for functional domain
#' @param time vector of time points
#' @param penalties List of smoothing penalties for mean structure
#' @param indices_mean Maps penalties in the mean structure to beta coefficients
#' @param kdim Dimension of latent subspace
#' @param iter Number of iterations to run
#' @param burnin Number of iterations to use as burn-in. This is only relevant when
#' passing the returned object into post-processing functions
#' @param thin Thinning defaulting to 1
#' @export run_mcmc
#' @return A List containing 3 lists including data, control, and samples.
run_mcmc <- function(response, design, basis, time, penalty, ldim, iter, burnin, thin = 1L, init_ = NULL, covstruct = "partial") {
    .Call('_rrbfda_run_mcmc', PACKAGE = 'rrbfda', response, design, basis, time, penalty, ldim, iter, burnin, thin, init_, covstruct)
}

get_delta_eta_density <- function(delta_eta1, delta_eta2, eta, beta, xi_eta, design) {
    .Call('_rrbfda_get_delta_eta_density', PACKAGE = 'rrbfda', delta_eta1, delta_eta2, eta, beta, xi_eta, design)
}

get_delta_eta_proposal <- function(delta_eta1, delta_eta2) {
    .Call('_rrbfda_get_delta_eta_proposal', PACKAGE = 'rrbfda', delta_eta1, delta_eta2)
}

get_delta_eta1_grad <- function(delta_eta1, delta_eta2, eta, beta, xi_eta, design, r, c) {
    .Call('_rrbfda_get_delta_eta1_grad', PACKAGE = 'rrbfda', delta_eta1, delta_eta2, eta, beta, xi_eta, design, r, c)
}

get_delta_eta2_grad <- function(delta_eta1, delta_eta2, eta, beta, xi_eta, design, c, l) {
    .Call('_rrbfda_get_delta_eta2_grad', PACKAGE = 'rrbfda', delta_eta1, delta_eta2, eta, beta, xi_eta, design, c, l)
}

compute_delta_eta_density_c <- function(delta_eta1, delta_eta2, eta, beta, xi_eta, design, c, a1, a2, a3, a4) {
    .Call('_rrbfda_compute_delta_eta_density_c', PACKAGE = 'rrbfda', delta_eta1, delta_eta2, eta, beta, xi_eta, design, c, a1, a2, a3, a4)
}

compute_delta_eta_density_c2 <- function(delta_eta1, delta_eta2, delta_eta3, eta, beta, xi_eta, design, c) {
    .Call('_rrbfda_compute_delta_eta_density_c2', PACKAGE = 'rrbfda', delta_eta1, delta_eta2, delta_eta3, eta, beta, xi_eta, design, c)
}

identify_delta1 <- function(input) {
    .Call('_rrbfda_identify_delta1', PACKAGE = 'rrbfda', input)
}

identify_delta2 <- function(input) {
    .Call('_rrbfda_identify_delta2', PACKAGE = 'rrbfda', input)
}

gam_trunc_left <- function(a, b, cut) {
    .Call('_rrbfda_gam_trunc_left', PACKAGE = 'rrbfda', a, b, cut)
}

gam_trunc_right <- function(a, b, cut) {
    .Call('_rrbfda_gam_trunc_right', PACKAGE = 'rrbfda', a, b, cut)
}

normal_trunc_left <- function(a, b, cut) {
    .Call('_rrbfda_normal_trunc_left', PACKAGE = 'rrbfda', a, b, cut)
}

reshape_nreg <- function(eta, nsub, nreg) {
    .Call('_rrbfda_reshape_nreg', PACKAGE = 'rrbfda', eta, nsub, nreg)
}

compare_waic <- function(waic1, waic2) {
    .Call('_rrbfda_compare_waic', PACKAGE = 'rrbfda', waic1, waic2)
}

calculate_waic <- function(result) {
    .Call('_rrbfda_calculate_waic', PACKAGE = 'rrbfda', result)
}

