# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_pval <- function(eta, nreg, ldim) {
    .Call('_rbfda_get_pval', PACKAGE = 'rbfda', eta, nreg, ldim)
}

reshape_nreg <- function(eta, nsub, nreg) {
    .Call('_rbfda_reshape_nreg', PACKAGE = 'rbfda', eta, nsub, nreg)
}

postcheck <- function(mcmc, refdist_samples = 10000L) {
    .Call('_rbfda_postcheck', PACKAGE = 'rbfda', mcmc, refdist_samples)
}

#' @export
rcpparma_hello_world <- function() {
    .Call('_rbfda_rcpparma_hello_world', PACKAGE = 'rbfda')
}

rcpparma_outerproduct <- function(x) {
    .Call('_rbfda_rcpparma_outerproduct', PACKAGE = 'rbfda', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_rbfda_rcpparma_innerproduct', PACKAGE = 'rbfda', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_rbfda_rcpparma_bothproducts', PACKAGE = 'rbfda', x)
}

#' Run Markov-Chain Monte-Carlo
#'
#' Generate samples from the posterior distribution using Gibbs sampling and 
#' Metropolis-Hastings steps
#' @param response N x T response matrix, where N is number of subjects and T is number
#' of time points. Values can be NA if there's missing data
#' @param design N x d_{1} design matrix for mean structure
#' @param basis T x p basis matrix for functional domain
#' @param time vector of time points
#' @param penalties List of smoothing penalties for mean structure
#' @param indices_mean Maps penalties in the mean structure to beta coefficients
#' @param kdim Dimension of latent subspace
#' @param iter Number of iterations to run
#' @param burnin Number of iterations to use as burn-in. This is only relevant when
#' passing the returned object into post-processing functions
#' @param thin Thinning defaulting to 1
#' @export run_mcmc
#' @return A List containing 3 lists including data, control, and samples.
run_mcmc <- function(response, design, basis, time, penalty, ldim, iter, burnin, thin = 1L, init_ = NULL, covstruct = "partial") {
    .Call('_rbfda_run_mcmc', PACKAGE = 'rbfda', response, design, basis, time, penalty, ldim, iter, burnin, thin, init_, covstruct)
}

delta_eta_diff <- function(delta_eta1, delta_eta2, eta, beta, xi_eta, a1, a2, nsub, nreg, ldim, designdim, design) {
    .Call('_rbfda_delta_eta_diff', PACKAGE = 'rbfda', delta_eta1, delta_eta2, eta, beta, xi_eta, a1, a2, nsub, nreg, ldim, designdim, design)
}

